slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_topic: /map
    scan_topic: /scan
    map_update_interval: 1.0
    map_publish_period: 1.0
    resolution: 0.05
    max_laser_range: 50.0
    min_laser_range: 0.1
    publish_map: true
    publish_pose: true
    mode: "mapping"
    map_frame: map
    base_frame: base_link
    odom_frame: odom
    queue_size: 50
    optimize_every_n_nodes: 2
    publish_tf: true
